name: ledsync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^12.3.0
  battery_plus: ^7.0.0
  installed_apps: ^2.1.1
  flutter_notification_listener_plus: ^1.3.7
  shared_preferences: ^2.5.4
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/LH8n.png
    - assets/wild_ksu_icon.png
    - assets/ksu_icon.png
    - assets/kernelsu_next.png
    - assets/apatch_icon.png

flutter_launcher_icons:
  android: true
  image_path: "assets/App_Logo.jpg"
